[package]
name = "bento"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
clap = { version = "4.5.21", features = [
    "cargo",
    "derive",
    "env",
    "unicode",
    "wrap_help",
] }
